/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var l=Object.defineProperty;var c=Object.getOwnPropertyDescriptor;var t=Object.getOwnPropertyNames;var g=Object.prototype.hasOwnProperty;var r=(e,o)=>{for(var a in o)l(e,a,{get:o[a],enumerable:!0})},b=(e,o,a,u)=>{if(o&&typeof o=="object"||typeof o=="function")for(let n of t(o))!g.call(e,n)&&n!==a&&l(e,n,{get:()=>o[n],enumerable:!(u=c(o,n))||u.enumerable});return e};var f=e=>b(l({},"__esModule",{value:!0}),e);var i={};r(i,{default:()=>d});module.exports=f(i);var s=require("obsidian"),d=class extends s.Plugin{async onload(){console.debug("Enhanced Callout Manager loaded")}onunload(){console.debug("Enhanced Callout Manager unloaded")}};
